export const subscriptionText = {
  zh: {
    title: '订阅管理',
    subtitle: '把订阅、刷新和应用分流放在一起。',
    active: '当前配置',
    sources: '订阅来源',
    nodes: '已加载节点',
    remote: '自动更新订阅',
    add: '添加订阅',
    refreshAll: '刷新全部',
    refresh: '立即刷新',
    edit: '编辑',
    remove: '移除',
    search: '搜索订阅或分流组',
    updated: '上次更新',
    never: '尚未更新',
    every: '每 {n} 分钟更新',
    manual: '手动更新',
    local: '本地来源',
    http: '远程订阅',
    ready: '已加载',
    pending: '等待加载',
    groups: '加入分流组',
    automatic: '自动包含所有订阅',
    noGroups: '尚未加入分流组',
    localNote: '本地节点文件，无远程订阅链接。',
    name: '订阅名称',
    url: '订阅链接',
    minutes: '自动刷新间隔（分钟）',
    urlHelp: '填写 Clash / Mihomo YAML 订阅链接，链接仅保存在本机。',
    groupHelp: '新节点会加入所选分流组；原有规则和当前选择保持不变。',
    save: '保存并生效',
    cancel: '取消',
    close: '关闭',
    saving: '正在校验并应用…',
    saved: '订阅配置已保存并生效',
    refreshed: '刷新成功',
    removed: '订阅已移除',
    partialRefresh: '部分订阅刷新失败：',
    confirmRemove: '移除订阅',
    removeHelp:
      '将移除此订阅及它在分流组中的引用。其他订阅和分流规则保持不变。',
    refreshHint: '续费或更新节点后，点击“立即刷新”，无需等待自动更新。',
    localOnly: '请先启用本地聚合配置。远程订阅会在更新时覆盖修改。',
    empty: '还没有订阅来源。添加一个订阅，然后选择要加入的分流组。',
    noMatches: '没有匹配的订阅',
    retry: '重新加载',
    loading: '正在读取当前订阅…',
    invalidConfig: '配置格式不正确，未作修改。',
    invalidName: '请填写有效的订阅名称（最多 80 字）。',
    duplicateName: '这个订阅名称已经存在。',
    invalidUrl: '请填写有效的 HTTP 或 HTTPS 订阅链接。',
    invalidInterval: '更新间隔必须为 1 到 10080 之间的整数分钟。',
    chooseGroups: '请至少选择一个分流组。',
    configChanged: '配置已被其他操作修改，请重新加载后再保存。',
    emptyGroup:
      '此操作会清空某个分流组，请先在 Clash 中为该组加入其他来源或节点。',
    localSource: '本地来源不能修改为远程订阅。',
    validationFailed:
      '新配置未通过内核校验，原配置已保留。请检查订阅链接和分流组。',
    applyFailed:
      '配置应用失败，已尝试恢复原配置。请检查 Clash 状态后重新加载。',
    busy: '另一个操作正在进行，请稍后再试。',
    unavailable: '暂时无法连接 Clash，请确认客户端正在运行。',
    generic: '操作未完成，请检查 Clash 和订阅服务后重试。',
    expiry: '到期时间',
    expired: '订阅已到期',
    expiresUnknown: '未提供到期时间',
  },
  en: {
    title: 'Subscriptions',
    subtitle: 'Subscriptions, updates and app routing in one place.',
    active: 'Active profile',
    sources: 'Sources',
    nodes: 'Loaded nodes',
    remote: 'Auto-updating sources',
    add: 'Add subscription',
    refreshAll: 'Refresh all',
    refresh: 'Refresh now',
    edit: 'Edit',
    remove: 'Remove',
    search: 'Search subscriptions or groups',
    updated: 'Last updated',
    never: 'Not updated yet',
    every: 'Every {n} minutes',
    manual: 'Manual updates',
    local: 'Local source',
    http: 'Remote subscription',
    ready: 'Loaded',
    pending: 'Not loaded',
    groups: 'Routing groups',
    automatic: 'Includes all subscriptions automatically',
    noGroups: 'No routing groups',
    localNote: 'Local node file without a subscription URL.',
    name: 'Subscription name',
    url: 'Subscription URL',
    minutes: 'Update interval (minutes)',
    urlHelp:
      'Use a Clash / Mihomo YAML subscription URL. It stays on this device.',
    groupHelp:
      'Add nodes to these groups while keeping existing rules and selections.',
    save: 'Save and apply',
    cancel: 'Cancel',
    close: 'Close',
    saving: 'Validating and applying…',
    saved: 'Subscription saved and applied',
    refreshed: 'Refresh completed',
    removed: 'Subscription removed',
    partialRefresh: 'Some subscriptions failed to refresh: ',
    confirmRemove: 'Remove subscription',
    removeHelp:
      'Remove this source and its group references. Other subscriptions and rules are kept.',
    refreshHint:
      'Renewed your plan? Refresh now instead of waiting for the next automatic update.',
    localOnly:
      'Activate a local aggregate profile first. Remote profiles overwrite edits when updated.',
    empty: 'No sources yet. Add a subscription and choose its routing groups.',
    noMatches: 'No matching subscriptions',
    retry: 'Reload',
    loading: 'Reading active subscriptions…',
    invalidConfig: 'Invalid configuration. Nothing was changed.',
    invalidName: 'Enter a valid name (up to 80 characters).',
    duplicateName: 'This name already exists.',
    invalidUrl: 'Enter a valid HTTP or HTTPS subscription URL.',
    invalidInterval: 'Use an integer interval between 1 and 10080 minutes.',
    chooseGroups: 'Select at least one routing group.',
    configChanged: 'The configuration changed elsewhere. Reload before saving.',
    emptyGroup:
      'This would empty a routing group. Add another source or node to that group in Clash first.',
    localSource: 'A local source cannot be edited as a remote subscription.',
    validationFailed:
      'Core validation failed. The previous configuration was kept. Check the URL and routing groups.',
    applyFailed:
      'Could not apply changes. Restoration was attempted. Check Clash and reload.',
    busy: 'Another operation is running. Try again shortly.',
    unavailable: 'Cannot connect to Clash. Make sure the client is running.',
    generic:
      'The operation did not complete. Check Clash and your subscription service, then retry.',
    expiry: 'Expires',
    expired: 'Subscription expired',
    expiresUnknown: 'No expiry information',
  },
}
